#-------------------------------
# General Site Settings

title: Deep Vision Centre
description: Computer Vision Software Repository
email: deepvision.centre@gmail.com


#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Computer Vision POC Software website. With deep learning projects for testing purposes.'
  rel-author: 'https://github.com/ashishrana160796'
  rel-publisher: 'https://github.com/ashishrana160796'
